name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, nightly]
    steps:
    - uses: actions/checkout@master
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: llvm-tools-preview, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Install latest nextest release
      uses: taiki-e/install-action@nextest
    # - name: Install cargo-llvm-cov
    #   uses: taiki-e/install-action@cargo-llvm-cov
    # - name: Collect coverage data
    #   run: cargo llvm-cov nextest --workspace  --codecov --output-path codecov.json
    # - name: Upload to codecov.io
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     files: codecov.json
        # fail_ci_if_error: true
    - name: Format
      run: cargo fmt --all -- --check
    - name: Docs
      run: cargo doc --no-deps
